apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sql-secret
                  key: SA_PASSWORD
          volumeMounts:
            - name: sql-data
              mountPath: /var/opt/mssql
          resources:
            requests:
              memory: "2Gi"
            limits:
              memory: "2Gi"
      volumes:
        - name: sql-data
          persistentVolumeClaim:
            claimName: sql-data-pvc